### ISSUE TITLE
成功编译simple_proxy_asio，但是怎么使用？

### ISSUE THREAD

**Issue by luckypoem** [ccsexyz/simple-proxy-asio#1]
hi.

root@ar:~/simple-proxy-asio/build# ./simple_proxy_asio -h
Exception: stoi
root@ar:~/simple-proxy-asio/build# ./simple_proxy_asio --help
Exception: stoi
root@ar:~/simple-proxy-asio/build#

**Comment by ccsexyz** [comment]
你为啥要用这个，应该直接使用shadowsocks
